source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
inhibit_all_warnings!

target 'SimcoeExample’ do

    pod 'Simcoe', :subspecs => ['Adobe', 'mParticle'], git: 'https://github.com/prolificinteractive/simcoe.git', branch: 'feature/swift3'

end
